
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - image: 410986195230.dkr.ecr.us-west-2.amazonaws.com/auth:00000001
        imagePullPolicy: Always
        name: auth
        ports:
        - protocol: TCP
          containerPort: 40404
          containerPort: 40405
        env:
        - name: ENVIRONMENT
          value: "STAGE"
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 40404
      name: port-1
      targetPort: 40404
    - protocol: TCP
      port: 40405
      name: port-2
      targetPort: 40405
    