
apiVersion: apps/v1
kind: Deployment
metadata:
  name: billing
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: billing
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: billing
    spec:
      containers:
      - image: 410986195230.dkr.ecr.us-west-2.amazonaws.com/billing:00000001
        imagePullPolicy: Always
        name: billing
        ports:
        - protocol: TCP
          containerPort: 40404
        env:
        - name: ENVIRONMENT
          value: "STAGE"
---
apiVersion: v1
kind: Service
metadata:
  name: billing
spec:
  selector:
    app: billing
  ports:
    - protocol: TCP
      port: 40404
      name: port-1
      targetPort: 40404