
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ltl-api-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: miranda
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: miranda
    spec:
      containers:
      - image: 410986195230.dkr.ecr.us-west-2.amazonaws.com/ltl-api-service:00000001
        imagePullPolicy: Always
        name: ltl-api-service
        ports:
        - protocol: TCP
          containerPort: 40404
        env:
        - name: ENVIRONMENT
          value: "STAGE"
        - name: P44_BASE_URL
          value: "https://test.p-44.com"
        - name: P44_DOCUMENTS_BASE_URL
          value: "https://cloud.p-44.com"
---
apiVersion: v1
kind: Service
metadata:
  name: ltl-api-service
spec:
  selector:
    app: miranda
  ports:
   -  protocol: TCP
      port: 40404
      targetPort: 40404
