
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rate-limit-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rate-limit-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: rate-limit-service
    spec:
      containers:
      - image: 410986195230.dkr.ecr.us-west-2.amazonaws.com/rate-limit-service:00000001
        imagePullPolicy: Always
        name: rate-limit-service
        ports:
        - protocol: TCP
          containerPort: 40404
        env:
        - name: ENVIRONMENT
          value: "STAGE"
---
apiVersion: v1
kind: Service
metadata:
  name: rate-limit-service
spec:
  selector:
    app: rate-limit-service
  ports:
   -  protocol: TCP
      port: 40404
      targetPort: 40404