
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse-proxy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: miranda
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: miranda
    spec:
      containers:
      - image: 410986195230.dkr.ecr.us-west-2.amazonaws.com/reverse-proxy:00000004
        imagePullPolicy: Always
        name: reverse-proxy
        ports:
        - protocol: TCP
          containerPort: 80
        env:
        - name: ENVIRONMENT
          value: "STAGE"
---
apiVersion: v1
kind: Service
metadata:
  name: reverse-proxy
spec:
  selector:
    app: miranda
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 80
