
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-order-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tms-order-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tms-order-service
    spec:
      containers:
      - image: 410986195230.dkr.ecr.us-west-2.amazonaws.com/tms-order-service:00000001
        imagePullPolicy: Always
        name: tms-order-service
        ports:
        - protocol: TCP
          containerPort: 40404
        env:
        - name: ENVIRONMENT
          value: "STAGE"
        - name: TRACK_QUEUE_LIMIT
          value: "50"
        - name: MONGO_URL
          value: "mongodb+srv://{auth}@miranda-dev.6c2la.mongodb.net/myFirstDatabase?retryWrites=true&w=majority/{name}"
        - name: MONGO_AUTH
          value: "test:test123"
        - name: RABBITMQ_URL
          value: "amqps://wwhxgeff:QoJ06A16BhBBo1Tw7BICuLIzAeMy6-Z9@snake.rmq2.cloudamqp.com/wwhxgeff"
        - name: REDIS_URL
          value: "redis-16445.c1.us-west-2-2.ec2.cloud.redislabs.com"
        - name: REDIS_PORT
          value: "16445"
        - name: REDIS_PASSWORD
          value: "uweBGRjRxBRO5DqHezqhkMaAVgIVxY2O" 
---
apiVersion: v1
kind: Service
metadata:
  name: tms-order-service
spec:
  selector:
    app: tms-order-service
  ports:
   -  protocol: TCP
      port: 40404
      targetPort: 40404
