
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-customer-portal-ui
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tms-customer-portal-ui
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tms-customer-portal-ui
    spec:
      containers:
      - image: 410986195230.dkr.ecr.us-west-2.amazonaws.com/tms-customer-portal-ui:00000001
        imagePullPolicy: Always
        name: tms-customer-portal-ui
        ports:
        - protocol: TCP
          containerPort: 40404
        env:
        - name: ENVIRONMENT
          value: "STAGE"
---
apiVersion: v1
kind: Service
metadata:
  name: tms-customer-portal-ui
spec:
  selector:
    app: tms-customer-portal-ui
  ports:
   -  protocol: TCP
      port: 40404
      targetPort: 40404