
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-order-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: miranda
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: miranda
    spec:
      containers:
      - image: 410986195230.dkr.ecr.us-west-2.amazonaws.com/tms-order-service:00000001
        imagePullPolicy: Always
        name: tms-order-service
        ports:
        - protocol: TCP
          containerPort: 40404
        env:
        - name: ENVIRONMENT
          value: "STAGE"
        - name: TRACK_QUEUE_LIMIT
          value: "50"
        - name: MONGO_URL
          value: "mongodb+srv://{auth}@miranda-dev.6c2la.mongodb.net/myFirstDatabase?retryWrites=true&w=majority/{name}"
        - name: MONGO_AUTH
          value: "test:test123"
        - name: RABBITMQ_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
        - name: REDIS_URL
          value: "redis-api"          
        - name: REDIS_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: tms-order-service
spec:
  selector:
    app: miranda
  ports:
   -  protocol: TCP
      port: 40404
      targetPort: 40404
