
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tms-company-service
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tms-company-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: tms-company-service
    spec:
      containers:
      - image: 410986195230.dkr.ecr.us-west-2.amazonaws.com/tms-company-service:00000001
        imagePullPolicy: Always
        name: tms-company-service
        ports:
        - protocol: TCP
          containerPort: 40404
        env:
        - name: ENVIRONMENT
          value: "STAGE"
        - name: MONGO_URL
          value: "mongodb+srv://{auth}@miranda-dev.6c2la.mongodb.net/myFirstDatabase?retryWrites=true&w=majority/{name}"
        - name: MONGO_AUTH
          value: "test:test123"
        - name: RABBITMQ_URL
          value: "amqps://wwhxgeff:QoJ06A16BhBBo1Tw7BICuLIzAeMy6-Z9@snake.rmq2.cloudamqp.com/wwhxgeff"
---
apiVersion: v1
kind: Service
metadata:
  name: tms-company-service
spec:
  selector:
    app: tms-company-service
  ports:
   -  protocol: TCP
      port: 40404
      targetPort: 40404
