
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-ui
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: miranda
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: miranda
    spec:
      containers:
      - image: 410986195230.dkr.ecr.us-west-2.amazonaws.com/web-ui:00000001
        imagePullPolicy: Always
        name: web-ui
        ports:
        - protocol: TCP
          containerPort: 42301
        env:
        - name: ENVIRONMENT
          value: "STAGE"
---
apiVersion: v1
kind: Service
metadata:
  name: web-ui
spec:
  selector:
    app: miranda
  ports:
   -  protocol: TCP
      port: 42301
      targetPort: 42301